baseURL = "https://aswanipranjal.github.io/"
languageCode = "en-us"
title = "TOBOR A TON MA I"
theme = "coder"

[params] # theme parameters
    author = "Pranjal Aswani" # author's name
    info = "Python Developer" # author's job title or info
    description = "This is where i will rant about stuff" # site description
    keywords = "blog,developer,personal" # site keywords
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/aswanipranjal"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/AswaniPranjal"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/pranjal-aswani-912bb8a3"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
